version: '3'
services:
  db_person:
    image: mysql
    container_name: db_person_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      - "3306:3306"
    volumes:
      - "./scripts/db_person_create.sql:/docker-entrypoint-initdb.d/1.sql"
    networks:
      - default
  
  db_products:
    image: mysql
    container_name: db_products_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      - "3307:3306"
    volumes:
      - "./scripts/db_products_create.sql:/docker-entrypoint-initdb.d/1.sql"
    networks:
      - default

  ms_person:
    build:
      "./person"
    container_name: ms_person
    restart: always
    ports:
      - "8080:8080"
    networks:
      - default
    profiles:
      - dev
    environment:
       - "SPRING_PROFILES_ACTIVE=dev"

  ms_products:
    build:
      "./products"
    container_name: ms_products
    restart: always
    ports:
      - "8081:8080"
    networks:
      - default
    profiles:
      - dev
    environment:
       - "SPRING_PROFILES_ACTIVE=dev"  
  
networks:
  default:
    driver: bridge
